/*
 * OpenGL shader sources for the Slayer 3D renderer.
 */

#include "gl_renderer_shaders.h"

const char k_pbr_vert[] = "layout(location = 0) in vec3 aPosition;\n"
                          "layout(location = 1) in vec3 aNormal;\n"
                          "layout(location = 2) in vec2 aTexCoord;\n"
                          "layout(location = 3) in vec4 aColor;\n"
                          "layout(location = 4) in vec2 aLightmapUV;\n"
                          "layout(location = 5) in vec4 aInstanceModel0;\n"
                          "layout(location = 6) in vec4 aInstanceModel1;\n"
                          "layout(location = 7) in vec4 aInstanceModel2;\n"
                          "layout(location = 8) in vec4 aInstanceModel3;\n"
                          "layout(location = 9) in vec3 aInstanceNormal0;\n"
                          "layout(location = 10) in vec3 aInstanceNormal1;\n"
                          "layout(location = 11) in vec3 aInstanceNormal2;\n"
                          "layout(location = 12) in vec4 aJointIndices;\n"
                          "layout(location = 13) in vec4 aJointWeights;\n"
                          "\n"
                          "#define MAX_LIGHTS 8\n"
                          "#define MAX_SKIN_JOINTS 64\n"
                          "#define MAX_SKIN_PALETTE_MATRICES 256\n"
                          "struct Light {\n"
                          "    int type;\n"
                          "    vec3 position;\n"
                          "    vec3 direction;\n"
                          "    vec3 color;\n"
                          "    float intensity;\n"
                          "    float range;\n"
                          "    float innerCutoff;\n"
                          "    float outerCutoff;\n"
                          "};\n"
                          "layout(std140) uniform SceneUBO {\n"
                          "    mat4 uViewProjection;\n"
                          "    vec3 uCameraPos;\n"
                          "    float _pad0;\n"
                          "    vec3 uAmbient;\n"
                          "    int uLightCount;\n"
                          "    Light uLights[MAX_LIGHTS];\n"
                          "    int uFogMode;\n"
                          "    float uFogStart;\n"
                          "    float uFogEnd;\n"
                          "    float uFogDensity;\n"
                          "    vec3 uFogColor;\n"
                          "    int uTonemapMode;\n"
                          "};\n"
                          "\n"
                          "uniform mat4 uModel;\n"
                          "uniform mat3 uNormalMatrix;\n"
                          "uniform int uUseInstancing;\n"
                          "uniform int uUseSkinning;\n"
                          "uniform int uUseSkinPalette;\n"
                          "uniform int uJointPaletteOffset;\n"
                          "uniform mat4 uJointMatrices[MAX_SKIN_JOINTS];\n"
                          "layout(std140) uniform SkinPaletteUBO {\n"
                          "    mat4 uSkinPalette[MAX_SKIN_PALETTE_MATRICES];\n"
                          "};\n"
                          "\n"
                          "out vec3 vWorldPos;\n"
                          "out vec3 vWorldNormal;\n"
                          "out vec2 vTexCoord;\n"
                          "out vec2 vLightmapUV;\n"
                          "out vec4 vColor;\n"
                          "\n"
                          "mat4 skinJointMatrix(float jointIndex) {\n"
                          "    int uniformJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_JOINTS - 1)));\n"
                          "    int paletteJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_PALETTE_MATRICES - "
                          "1)));\n"
                          "    return (uUseSkinPalette != 0) ? uSkinPalette[uJointPaletteOffset + "
                          "paletteJoint] : uJointMatrices[uniformJoint];\n"
                          "}\n"
                          "\n"
                          "void main() {\n"
                          "    mat4 model = (uUseInstancing != 0) ? mat4(aInstanceModel0, aInstanceModel1, "
                          "aInstanceModel2, aInstanceModel3) : uModel;\n"
                          "    mat3 normalMatrix = (uUseInstancing != 0) ? mat3(aInstanceNormal0, "
                          "aInstanceNormal1, aInstanceNormal2) : uNormalMatrix;\n"
                          "    vec4 localPos = vec4(aPosition, 1.0);\n"
                          "    vec3 localNormal = aNormal;\n"
                          "    if (uUseSkinning != 0) {\n"
                          "        mat4 skin = aJointWeights.x * skinJointMatrix(aJointIndices.x)\n"
                          "                  + aJointWeights.y * skinJointMatrix(aJointIndices.y)\n"
                          "                  + aJointWeights.z * skinJointMatrix(aJointIndices.z)\n"
                          "                  + aJointWeights.w * skinJointMatrix(aJointIndices.w);\n"
                          "        localPos = skin * localPos;\n"
                          "        localNormal = mat3(skin) * localNormal;\n"
                          "    }\n"
                          "    vec4 worldPos = model * localPos;\n"
                          "    vWorldPos = worldPos.xyz;\n"
                          "    vWorldNormal = normalize(normalMatrix * localNormal);\n"
                          "    vTexCoord = aTexCoord;\n"
                          "    vLightmapUV = aLightmapUV;\n"
                          "    vColor = aColor;\n"
                          "    gl_Position = uViewProjection * worldPos;\n"
                          "}\n";

const char k_pbr_frag_decl[] =
    "#define MAX_LIGHTS 8\n"
    "#define PI 3.14159265\n"
    "\n"
    "struct Light {\n"
    "    int type;\n"
    "    vec3 position;\n"
    "    vec3 direction;\n"
    "    vec3 color;\n"
    "    float intensity;\n"
    "    float range;\n"
    "    float innerCutoff;\n"
    "    float outerCutoff;\n"
    "};\n"
    "\n"
    "layout(std140) uniform SceneUBO {\n"
    "    mat4 uViewProjection;\n"
    "    vec3 uCameraPos;\n"
    "    float _pad0;\n"
    "    vec3 uAmbient;\n"
    "    int uLightCount;\n"
    "    Light uLights[MAX_LIGHTS];\n"
    "    int uFogMode;\n"
    "    float uFogStart;\n"
    "    float uFogEnd;\n"
    "    float uFogDensity;\n"
    "    vec3 uFogColor;\n"
    "    int uTonemapMode;\n"
    "};\n"
    "\n"
    "in vec3 vWorldPos;\n"
    "in vec3 vWorldNormal;\n"
    "in vec2 vTexCoord;\n"
    "in vec2 vLightmapUV;\n"
    "in vec4 vColor;\n"
    "\n"
    "uniform sampler2D uTexture;\n"
    "uniform int uHasTexture;\n"
    "uniform sampler2D uLightmap;\n"
    "uniform int uHasLightmap;\n"
    "uniform vec4 uTint;\n"
    "uniform float uMetallic;\n"
    "uniform float uRoughness;\n"
    "uniform vec3 uEmissive;\n"
    "uniform int uBakedLightMode;\n"
    "\n"
    "uniform sampler2DArray uShadowMap;\n"
    "uniform mat4 uShadowVP;\n"
    "uniform int uShadowEnabled;\n"
    "uniform float uShadowBias;\n"
    "uniform mat4 uCSMVP[4];\n"
    "uniform float uCSMSplits[4];\n"
    "uniform mat4 uViewMatrix;\n"
    "uniform int uCSMEnabled;\n"
    "\n"
    "uniform samplerCube uPointShadowMap[2];\n"
    "uniform vec3 uPointShadowLightPos[2];\n"
    "uniform float uPointShadowFar[2];\n"
    "uniform int uPointShadowCount;\n"
    "\n"
    "uniform samplerCube uIrradianceMap;\n"
    "uniform samplerCube uPrefilterMap;\n"
    "uniform sampler2D uBrdfLUT;\n"
    "uniform int uIBLEnabled;\n"
    "uniform float uMaxReflectionLod;\n"
    "\n"
    "out vec4 fragColor;\n"
    "\n"
    "float DistributionGGX(float NdotH, float r) {\n"
    "    float a = r * r;\n"
    "    float a2 = a * a;\n"
    "    float d = NdotH * NdotH * (a2 - 1.0) + 1.0;\n"
    "    return a2 / (PI * d * d + 0.0001);\n"
    "}\n"
    "\n"
    "float GeometrySchlickGGX(float NdotV, float r) {\n"
    "    float k = (r + 1.0) * (r + 1.0) / 8.0;\n"
    "    return NdotV / (NdotV * (1.0 - k) + k + 0.0001);\n"
    "}\n"
    "\n"
    "vec3 FresnelSchlick(float cosTheta, vec3 F0) {\n"
    "    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);\n"
    "}\n"
    "vec3 FresnelSchlickRoughness(float cosTheta, vec3 F0, float roughness) {\n"
    "    return F0 + (max(vec3(1.0 - roughness), F0) - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);\n"
    "}\n";

const char k_pbr_frag_main[] =
    "void main() {\n"
    "    vec2 uv = vTexCoord;\n"
    "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
    "    vec3 albedo = texel.rgb * ((uBakedLightMode != 0) ? uTint.rgb : (vColor.rgb * uTint.rgb));\n"
    "    float alpha = texel.a * vColor.a * uTint.a;\n"
    "    if (alpha <= 0.0) discard;\n"
    "\n"
    "    vec3 N = normalize(vWorldNormal);\n"
    "    vec3 V = normalize(uCameraPos - vWorldPos);\n"
    "    float NdotV = max(dot(N, V), 0.0);\n"
    "    vec3 F0 = mix(vec3(0.04), albedo, uMetallic);\n"
    "\n"
    "    vec3 Lo = vec3(0.0);\n"
    "    for (int i = 0; i < uLightCount && i < MAX_LIGHTS; i++) {\n"
    "        vec3 L;\n"
    "        float attenuation = 1.0;\n"
    "\n"
    "        if (uLights[i].type == 0) {\n"
    "            L = normalize(-uLights[i].direction);\n"
    "        } else {\n"
    "            vec3 toLight = uLights[i].position - vWorldPos;\n"
    "            float dist = length(toLight);\n"
    "            L = toLight / max(dist, 0.0001);\n"
    "            if (uLights[i].range > 0.0) {\n"
    "                float r = dist / uLights[i].range;\n"
    "                attenuation = max(1.0 - r * r, 0.0);\n"
    "                attenuation *= attenuation;\n"
    "            }\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                attenuation *= clamp((cosA - uLights[i].outerCutoff) / max(eps, 0.0001), 0.0, 1.0);\n"
    "            }\n"
    "        }\n"
    "\n"
    "        vec3 radiance = uLights[i].color * uLights[i].intensity * attenuation;\n"
    "        float NdotL = (uBakedLightMode != 0) ? abs(dot(N, L)) : max(dot(N, L), 0.0);\n"
    "        if (NdotL <= 0.0) continue;\n"
    "        if (uBakedLightMode != 0) {\n"
    "            Lo += albedo * radiance * NdotL;\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        vec3 H = normalize(L + V);\n"
    "        float NdotH = max(dot(N, H), 0.0);\n"
    "        float HdotV = max(dot(H, V), 0.0);\n"
    "\n"
    "        float NDF = DistributionGGX(NdotH, uRoughness);\n"
    "        float G = GeometrySchlickGGX(NdotV, uRoughness) * GeometrySchlickGGX(NdotL, uRoughness);\n"
    "        vec3 F = FresnelSchlick(HdotV, F0);\n"
    "\n"
    "        vec3 spec = (NDF * G * F) / (4.0 * NdotV * NdotL + 0.0001);\n"
    "        vec3 kD = (1.0 - F) * (1.0 - uMetallic);\n"
    "        vec3 diff = kD * albedo / PI;\n"
    "\n"
    "        Lo += (diff + spec) * radiance * NdotL;\n"
    "    }\n";

const char k_pbr_frag_shadow_post[] =
    "\n"
    "    vec3 color;\n"
    "    if (uBakedLightMode != 0) {\n"
    "        vec3 bakedLight = (uHasLightmap != 0) ? texture(uLightmap, vLightmapUV).rgb : vColor.rgb;\n"
    "        vec3 bakedBaseColor = texel.rgb * bakedLight * uTint.rgb;\n"
    "        color = bakedBaseColor + Lo + uEmissive;\n"
    "    } else {\n"
    "        /* Shadow (CSM cascade selection with PCF 3x3). */\n"
    "        if (uShadowEnabled != 0) {\n"
    "            int layer = 0;\n"
    "            if (uCSMEnabled != 0) {\n"
    "                float fragDepth = abs((uViewMatrix * vec4(vWorldPos, 1.0)).z);\n"
    "                layer = 3;\n"
    "                for (int i = 0; i < 4; ++i) {\n"
    "                    if (fragDepth < uCSMSplits[i]) { layer = i; break; }\n"
    "                }\n"
    "            }\n"
    "            mat4 shadowVP = (uCSMEnabled != 0) ? uCSMVP[layer] : uShadowVP;\n"
    "            vec4 lpos = shadowVP * vec4(vWorldPos, 1.0);\n"
    "            vec3 projCoords = lpos.xyz / lpos.w * 0.5 + 0.5;\n"
    "            float currentDepth = projCoords.z;\n"
    "            vec3 lightDir = normalize(-uLights[0].direction);\n"
    "            float bias = max(0.05 * (1.0 - dot(N, lightDir)), 0.005);\n"
    "            float shadow = 0.0;\n"
    "            vec2 texelSize = 1.0 / vec2(2048.0);\n"
    "            for (int x = -1; x <= 1; ++x) {\n"
    "                for (int y = -1; y <= 1; ++y) {\n"
    "                    float pcfDepth = texture(uShadowMap, vec3(projCoords.xy + vec2(x, y) * texelSize, "
    "float(layer))).r;\n"
    "                    shadow += currentDepth - bias > pcfDepth ? 1.0 : 0.0;\n"
    "                }\n"
    "            }\n"
    "            shadow /= 9.0;\n"
    "            if (projCoords.z > 1.0) shadow = 0.0;\n"
    "            /* Outside the shadow map means unshadowed. Desktop GL gets\n"
    "               this from CLAMP_TO_BORDER with a white border; ES 3.0 has\n"
    "               no border clamp, so guard the UVs here for both. */\n"
    "            if (projCoords.x < 0.0 || projCoords.x > 1.0 || projCoords.y < 0.0 || projCoords.y > 1.0) shadow = "
    "0.0;\n"
    "            Lo *= (1.0 - shadow);\n"
    "        }\n"
    "\n"
    "        /* Point light shadows. Keep sampler indexes constant for GLSL drivers\n"
    "         * that reject dynamic indexing into sampler arrays. */\n"
    "        if (uPointShadowCount > 0) {\n"
    "            vec3 fragToLight = vWorldPos - uPointShadowLightPos[0];\n"
    "            float closestDepth = texture(uPointShadowMap[0], fragToLight).r * uPointShadowFar[0];\n"
    "            float currentDepth = length(fragToLight);\n"
    "            float pbias = 0.15;\n"
    "            if (currentDepth - pbias > closestDepth) {\n"
    "                Lo *= 0.5;\n"
    "            }\n"
    "        }\n"
    "        if (uPointShadowCount > 1) {\n"
    "            vec3 fragToLight = vWorldPos - uPointShadowLightPos[1];\n"
    "            float closestDepth = texture(uPointShadowMap[1], fragToLight).r * uPointShadowFar[1];\n"
    "            float currentDepth = length(fragToLight);\n"
    "            float pbias = 0.15;\n"
    "            if (currentDepth - pbias > closestDepth) {\n"
    "                Lo *= 0.5;\n"
    "            }\n"
    "        }\n";

const char k_pbr_frag_light_post[] =
    "\n"
    "        /* Ambient: IBL when available, hemisphere fallback. */\n"
    "        vec3 ambient;\n"
    "        if (uIBLEnabled != 0) {\n"
    "            vec3 F_ibl = FresnelSchlickRoughness(NdotV, F0, uRoughness);\n"
    "            vec3 kS_ibl = F_ibl;\n"
    "            vec3 kD_ibl = (1.0 - kS_ibl) * (1.0 - uMetallic);\n"
    "            vec3 irradiance = texture(uIrradianceMap, N).rgb;\n"
    "            vec3 diffuse_ibl = irradiance * albedo;\n"
    "            vec3 R = reflect(-V, N);\n"
    "            vec3 prefilteredColor = textureLod(uPrefilterMap, R, uRoughness * uMaxReflectionLod).rgb;\n"
    "            vec2 brdf = texture(uBrdfLUT, vec2(NdotV, uRoughness)).rg;\n"
    "            vec3 specular_ibl = prefilteredColor * (F_ibl * brdf.x + brdf.y);\n"
    "            ambient = kD_ibl * diffuse_ibl + specular_ibl;\n"
    "        } else {\n"
    "            vec3 skyColor = uAmbient * 1.2;\n"
    "            vec3 groundColor = uAmbient * vec3(0.6, 0.5, 0.4);\n"
    "            float hemi = dot(N, vec3(0.0, 1.0, 0.0)) * 0.5 + 0.5;\n"
    "            ambient = mix(groundColor, skyColor, hemi) * albedo;\n"
    "        }\n"
    "        color = ambient + Lo + uEmissive;\n"
    "    }\n"
    "\n"
    "    if (uFogMode > 0) {\n"
    "        float dist = length(uCameraPos - vWorldPos);\n"
    "        float fogFactor = 0.0;\n"
    "        if (uFogMode == 1) fogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "        else if (uFogMode == 2) fogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "        else if (uFogMode == 3) { float d = uFogDensity * dist; fogFactor = 1.0 - exp(-d * d); }\n"
    "        color = mix(color, uFogColor, fogFactor);\n"
    "    }\n"
    "\n"
    "    if (uBakedLightMode == 0) {\n"
    "        if (uTonemapMode == 1) color = color / (1.0 + color);\n"
    "        else if (uTonemapMode == 2) {\n"
    "            float a = 2.51, b = 0.03, c = 2.43, d = 0.59, e = 0.14;\n"
    "            color = clamp((color * (a * color + b)) / (color * (c * color + d) + e), 0.0, 1.0);\n"
    "        }\n"
    "\n"
    "        color = pow(clamp(color, 0.0, 1.0), vec3(1.0 / 2.2));\n"
    "    } else {\n"
    "        color = clamp(color, 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "    fragColor = vec4(color, alpha);\n"
    "}\n";

const char k_unlit_vert[] = "layout(location = 0) in vec3 aPosition;\n"
                            "layout(location = 1) in vec2 aTexCoord;\n"
                            "layout(location = 2) in vec4 aColor;\n"
                            "\n"
                            "uniform mat4 uMVP;\n"
                            "\n"
                            "out vec2 vTexCoord;\n"
                            "out vec4 vColor;\n"
                            "\n"
                            "void main() {\n"
                            "    vTexCoord = aTexCoord;\n"
                            "    vColor = aColor;\n"
                            "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
                            "}\n";

const char k_unlit_frag[] = "in vec2 vTexCoord;\n"
                            "in vec4 vColor;\n"
                            "\n"
                            "uniform sampler2D uTexture;\n"
                            "uniform int uHasTexture;\n"
                            "uniform vec4 uTint;\n"
                            "uniform int uOverlayEffect;\n"
                            "uniform float uOverlayEffectProgress;\n"
                            "uniform float uOverlayEffectSeed;\n"
                            "uniform float uOverlayEffectColumns;\n"
                            "\n"
                            "out vec4 fragColor;\n"
                            "\n"
                            "float overlayHash(float n) {\n"
                            "    return fract(sin(n) * 43758.5453123);\n"
                            "}\n"
                            "\n"
                            "void main() {\n"
                            "    vec2 uv = vTexCoord;\n"
                            "    if (uOverlayEffect == 1) {\n"
                            "        float columns = max(uOverlayEffectColumns, 1.0);\n"
                            "        float column = floor(clamp(uv.x, 0.0, 0.999999) * columns);\n"
                            "        float rnd = overlayHash(column + uOverlayEffectSeed);\n"
                            "        float delay = rnd * 0.45;\n"
                            "        float melt = clamp((uOverlayEffectProgress - delay) / 0.55, 0.0, 1.0);\n"
                            "        float wobble = (rnd - 0.5) * 0.025 * melt;\n"
                            "        float yShift = melt * (1.05 + rnd * 0.6);\n"
                            "        uv = vec2(uv.x + wobble, uv.y - yShift);\n"
                            "        if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0) discard;\n"
                            "    }\n"
                            "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
                            "    fragColor = texel * vColor * uTint;\n"
                            "    if (fragColor.a <= 0.0) discard;\n"
                            "}\n";

const char k_fullscreen_vert[] = "out vec2 vTexCoord;\n"
                                 "\n"
                                 "void main() {\n"
                                 "    float x = float((gl_VertexID & 1) << 2) - 1.0;\n"
                                 "    float y = float((gl_VertexID & 2) << 1) - 1.0;\n"
                                 "    vTexCoord = vec2(x * 0.5 + 0.5, y * 0.5 + 0.5);\n"
                                 "    gl_Position = vec4(x, y, 0.0, 1.0);\n"
                                 "}\n";

const char k_copy_frag[] = "in vec2 vTexCoord;\n"
                           "uniform sampler2D uScene;\n"
                           "out vec4 fragColor;\n"
                           "\n"
                           "void main() {\n"
                           "    fragColor = texture(uScene, vTexCoord);\n"
                           "}\n";

const char k_skybox_frag[] =
    "in vec2 vTexCoord;\n"
    "uniform bool uPanorama;\n"
    "uniform sampler2D uSkySphere;\n"
    "uniform sampler2D uFacePosX;\n"
    "uniform sampler2D uFaceNegX;\n"
    "uniform sampler2D uFacePosY;\n"
    "uniform sampler2D uFaceNegY;\n"
    "uniform sampler2D uFacePosZ;\n"
    "uniform sampler2D uFaceNegZ;\n"
    "uniform vec3 uCameraRight;\n"
    "uniform vec3 uCameraUp;\n"
    "uniform vec3 uCameraForward;\n"
    "uniform vec2 uInvProjection;\n"
    "out vec4 fragColor;\n"
    "\n"
    "vec4 sampleSkySphere(vec3 direction) {\n"
    "    const float pi = 3.14159265358979323846;\n"
    "    const float tau = 6.28318530717958647692;\n"
    "    float u = atan(direction.x, direction.z) / tau + 0.5;\n"
    "    float v = 0.5 - asin(clamp(direction.y, -1.0, 1.0)) / pi;\n"
    "    return texture(uSkySphere, vec2(u, v));\n"
    "}\n"
    "\n"
    "vec4 sampleSkyboxAxis(vec3 direction, int axis) {\n"
    "    vec3 ad = abs(direction);\n"
    "    float majorAxis;\n"
    "    vec2 uv;\n"
    "    if (axis == 2) {\n"
    "        majorAxis = max(ad.z, 0.000001);\n"
    "        if (direction.z >= 0.0) {\n"
    "            uv = vec2(direction.x / majorAxis + 1.0, 1.0 - direction.y / majorAxis) * 0.5;\n"
    "            return texture(uFacePosX, uv);\n"
    "        }\n"
    "        uv = vec2(1.0 - direction.x / majorAxis, 1.0 - direction.y / majorAxis) * 0.5;\n"
    "        return texture(uFaceNegX, uv);\n"
    "    } else if (axis == 0) {\n"
    "        majorAxis = max(ad.x, 0.000001);\n"
    "        if (direction.x >= 0.0) {\n"
    "            uv = vec2(1.0 - direction.z / majorAxis, 1.0 - direction.y / majorAxis) * 0.5;\n"
    "            return texture(uFaceNegZ, uv);\n"
    "        }\n"
    "        uv = vec2(direction.z / majorAxis + 1.0, 1.0 - direction.y / majorAxis) * 0.5;\n"
    "        return texture(uFacePosZ, uv);\n"
    "    } else {\n"
    "        majorAxis = max(ad.y, 0.000001);\n"
    "        if (direction.y >= 0.0) {\n"
    "            uv = vec2(direction.z / majorAxis + 1.0, 1.0 - direction.x / majorAxis) * 0.5;\n"
    "            return texture(uFacePosY, uv);\n"
    "        }\n"
    "        uv = vec2(1.0 - direction.z / majorAxis, 1.0 - direction.x / majorAxis) * 0.5;\n"
    "        return texture(uFaceNegY, uv);\n"
    "    }\n"
    "}\n"
    "\n"
    "vec4 sampleSkyboxFace(vec3 direction) {\n"
    "    vec3 ad = abs(direction);\n"
    "    int majorAxis = 2;\n"
    "    float majorValue = ad.z;\n"
    "    int secondAxis = 0;\n"
    "    float secondValue = ad.x;\n"
    "    if (ad.x > majorValue) {\n"
    "        secondAxis = majorAxis;\n"
    "        secondValue = majorValue;\n"
    "        majorAxis = 0;\n"
    "        majorValue = ad.x;\n"
    "    } else if (ad.x > secondValue) {\n"
    "        secondAxis = 0;\n"
    "        secondValue = ad.x;\n"
    "    }\n"
    "    if (ad.y > majorValue) {\n"
    "        secondAxis = majorAxis;\n"
    "        secondValue = majorValue;\n"
    "        majorAxis = 1;\n"
    "        majorValue = ad.y;\n"
    "    } else if (ad.y > secondValue) {\n"
    "        secondAxis = 1;\n"
    "        secondValue = ad.y;\n"
    "    }\n"
    "    vec4 majorColor = sampleSkyboxAxis(direction, majorAxis);\n"
    "    float edgeGap = majorValue - secondValue;\n"
    "    const float seamFeather = 0.015;\n"
    "    if (edgeGap >= seamFeather) {\n"
    "        return majorColor;\n"
    "    }\n"
    "    vec4 secondColor = sampleSkyboxAxis(direction, secondAxis);\n"
    "    float majorWeight = smoothstep(0.0, seamFeather, edgeGap);\n"
    "    return mix(secondColor, majorColor, majorWeight);\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 ndc = vec2(vTexCoord.x * 2.0 - 1.0, vTexCoord.y * 2.0 - 1.0);\n"
    "    vec3 direction = normalize(uCameraForward + (uCameraRight * ndc.x * uInvProjection.x) +\n"
    "                               (uCameraUp * ndc.y * uInvProjection.y));\n"
    "    fragColor = uPanorama ? sampleSkySphere(direction) : sampleSkyboxFace(direction);\n"
    "}\n";

const char k_transition_frag[] =
    "in vec2 vTexCoord;\n"
    "uniform sampler2D uScene;\n"
    "uniform int uType;\n"
    "uniform int uDirection;\n"
    "uniform float uProgress;\n"
    "uniform vec4 uColor;\n"
    "uniform vec2 uResolution;\n"
    "uniform sampler2D uMeltOffsets;\n"
    "out vec4 fragColor;\n"
    "\n"
    "void main() {\n"
    "    vec4 scene = texture(uScene, vTexCoord);\n"
    "    float cover = (uDirection == 0) ? (1.0 - uProgress) : uProgress;\n"
    "    cover = clamp(cover, 0.0, 1.0);\n"
    "\n"
    "    if (uType == 0) {\n"
    "        fragColor = mix(scene, uColor, cover * uColor.a);\n"
    "    } else if (uType == 1) {\n"
    "        float aspect = uResolution.x / max(uResolution.y, 1.0);\n"
    "        vec2 centered = vTexCoord - vec2(0.5);\n"
    "        centered.x *= aspect;\n"
    "        float maxRadius = length(vec2(0.5 * aspect, 0.5));\n"
    "        float radius = maxRadius * (1.0 - cover);\n"
    "        vec4 covered = mix(scene, uColor, uColor.a);\n"
    "        fragColor = (length(centered) <= radius) ? scene : covered;\n"
    "    } else if (uType == 2) {\n"
    "        float offset = texture(uMeltOffsets, vec2(vTexCoord.x, 0.5)).r;\n"
    "        float columnProgress = clamp((cover - offset * 0.3) / 0.7, 0.0, 1.0);\n"
    "        float yShift = columnProgress * 1.5;\n"
    "        vec2 sampleUV = vec2(vTexCoord.x, vTexCoord.y - yShift);\n"
    "        vec4 covered = mix(scene, uColor, uColor.a);\n"
    "        fragColor = (sampleUV.y < 0.0) ? covered : texture(uScene, sampleUV);\n"
    "    } else if (uType == 3) {\n"
    "        float blockSize = mix(1.0, 64.0, cover);\n"
    "        vec2 safeResolution = max(uResolution, vec2(1.0));\n"
    "        vec2 pixelUV = floor(vTexCoord * safeResolution / blockSize) * blockSize / safeResolution;\n"
    "        vec4 pixelated = texture(uScene, pixelUV);\n"
    "        float colorBlend = smoothstep(0.7, 1.0, cover) * uColor.a;\n"
    "        fragColor = mix(pixelated, uColor, colorBlend);\n"
    "    } else {\n"
    "        fragColor = scene;\n"
    "    }\n"
    "}\n";

const char k_shadow_vert[] =
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 5) in vec4 iModel0;\n"
    "layout(location = 6) in vec4 iModel1;\n"
    "layout(location = 7) in vec4 iModel2;\n"
    "layout(location = 8) in vec4 iModel3;\n"
    "layout(location = 12) in vec4 aJointIndices;\n"
    "layout(location = 13) in vec4 aJointWeights;\n"
    "#define MAX_SKIN_JOINTS 64\n"
    "#define MAX_SKIN_PALETTE_MATRICES 256\n"
    "uniform mat4 uLightVP;\n"
    "uniform mat4 uModel;\n"
    "uniform int uUseInstancing;\n"
    "uniform int uUseSkinning;\n"
    "uniform int uUseSkinPalette;\n"
    "uniform int uJointPaletteOffset;\n"
    "uniform mat4 uJointMatrices[MAX_SKIN_JOINTS];\n"
    "layout(std140) uniform SkinPaletteUBO {\n"
    "    mat4 uSkinPalette[MAX_SKIN_PALETTE_MATRICES];\n"
    "};\n"
    "mat4 skinJointMatrix(float jointIndex) {\n"
    "    int uniformJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_JOINTS - 1)));\n"
    "    int paletteJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_PALETTE_MATRICES - 1)));\n"
    "    return (uUseSkinPalette != 0) ? uSkinPalette[uJointPaletteOffset + paletteJoint] : "
    "uJointMatrices[uniformJoint];\n"
    "}\n"
    "void main() {\n"
    "    mat4 model = (uUseInstancing != 0) ? mat4(iModel0, iModel1, iModel2, iModel3) : uModel;\n"
    "    vec4 localPos = vec4(aPosition, 1.0);\n"
    "    if (uUseSkinning != 0) {\n"
    "        mat4 skin = aJointWeights.x * skinJointMatrix(aJointIndices.x)\n"
    "                  + aJointWeights.y * skinJointMatrix(aJointIndices.y)\n"
    "                  + aJointWeights.z * skinJointMatrix(aJointIndices.z)\n"
    "                  + aJointWeights.w * skinJointMatrix(aJointIndices.w);\n"
    "        localPos = skin * localPos;\n"
    "    }\n"
    "    gl_Position = uLightVP * model * localPos;\n"
    "}\n";

const char k_shadow_frag[] = "out vec4 fragColor;\nvoid main() { fragColor = vec4(1.0); }\n";

const char k_point_shadow_vert[] =
    "layout(location = 0) in vec3 aPos;\n"
    "layout(location = 12) in vec4 aJointIndices;\n"
    "layout(location = 13) in vec4 aJointWeights;\n"
    "#define MAX_SKIN_JOINTS 64\n"
    "#define MAX_SKIN_PALETTE_MATRICES 256\n"
    "uniform mat4 model;\n"
    "uniform mat4 lightVP;\n"
    "uniform int uUseSkinning;\n"
    "uniform int uUseSkinPalette;\n"
    "uniform int uJointPaletteOffset;\n"
    "uniform mat4 uJointMatrices[MAX_SKIN_JOINTS];\n"
    "layout(std140) uniform SkinPaletteUBO {\n"
    "    mat4 uSkinPalette[MAX_SKIN_PALETTE_MATRICES];\n"
    "};\n"
    "out vec3 vWorldPos;\n"
    "mat4 skinJointMatrix(float jointIndex) {\n"
    "    int uniformJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_JOINTS - 1)));\n"
    "    int paletteJoint = int(clamp(jointIndex, 0.0, float(MAX_SKIN_PALETTE_MATRICES - 1)));\n"
    "    return (uUseSkinPalette != 0) ? uSkinPalette[uJointPaletteOffset + paletteJoint] : "
    "uJointMatrices[uniformJoint];\n"
    "}\n"
    "void main() {\n"
    "    vec4 localPos = vec4(aPos, 1.0);\n"
    "    if (uUseSkinning != 0) {\n"
    "        mat4 skin = aJointWeights.x * skinJointMatrix(aJointIndices.x)\n"
    "                  + aJointWeights.y * skinJointMatrix(aJointIndices.y)\n"
    "                  + aJointWeights.z * skinJointMatrix(aJointIndices.z)\n"
    "                  + aJointWeights.w * skinJointMatrix(aJointIndices.w);\n"
    "        localPos = skin * localPos;\n"
    "    }\n"
    "    vec4 wp = model * localPos;\n"
    "    vWorldPos = wp.xyz;\n"
    "    gl_Position = lightVP * wp;\n"
    "}\n";

const char k_point_shadow_frag[] = "in vec3 vWorldPos;\n"
                                   "uniform vec3 lightPos;\n"
                                   "uniform float farPlane;\n"
                                   "void main() {\n"
                                   "    float dist = length(vWorldPos - lightPos);\n"
                                   "    gl_FragDepth = dist / farPlane;\n"
                                   "}\n";

/* ---- Post-process fragment shaders ---- */

const char k_bloom_threshold_frag[] =
    "in vec2 vTexCoord;\n"
    "uniform sampler2D uScene;\n"
    "uniform float uThreshold;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec3 color = texture(uScene, vTexCoord).rgb;\n"
    "    float brightness = dot(color, vec3(0.2126, 0.7152, 0.0722));\n"
    "    fragColor = (brightness > uThreshold) ? vec4(color, 1.0) : vec4(0.0, 0.0, 0.0, 1.0);\n"
    "}\n";

const char k_blur_frag[] =
    "in vec2 vTexCoord;\n"
    "uniform sampler2D uImage;\n"
    "uniform int uHorizontal;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    float weights[5] = float[](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);\n"
    "    vec2 texOffset = 1.0 / vec2(textureSize(uImage, 0));\n"
    "    vec3 result = texture(uImage, vTexCoord).rgb * weights[0];\n"
    "    if (uHorizontal == 1) {\n"
    "        for (int i = 1; i < 5; ++i) {\n"
    "            result += texture(uImage, vTexCoord + vec2(texOffset.x * float(i), 0.0)).rgb * weights[i];\n"
    "            result += texture(uImage, vTexCoord - vec2(texOffset.x * float(i), 0.0)).rgb * weights[i];\n"
    "        }\n"
    "    } else {\n"
    "        for (int i = 1; i < 5; ++i) {\n"
    "            result += texture(uImage, vTexCoord + vec2(0.0, texOffset.y * float(i))).rgb * weights[i];\n"
    "            result += texture(uImage, vTexCoord - vec2(0.0, texOffset.y * float(i))).rgb * weights[i];\n"
    "        }\n"
    "    }\n"
    "    fragColor = vec4(result, 1.0);\n"
    "}\n";

const char k_composite_frag[] = "in vec2 vTexCoord;\n"
                                "uniform sampler2D uScene;\n"
                                "uniform sampler2D uBloom;\n"
                                "uniform float uVignetteStrength;\n"
                                "uniform float uContrast;\n"
                                "uniform float uSaturation;\n"
                                "out vec4 fragColor;\n"
                                "void main() {\n"
                                "    vec3 color = texture(uScene, vTexCoord).rgb;\n"
                                "    vec3 bloom = texture(uBloom, vTexCoord).rgb;\n"
                                "    color += bloom * 0.3;\n"
                                "    vec2 uv = vTexCoord * 2.0 - 1.0;\n"
                                "    float vig = 1.0 - dot(uv, uv) * uVignetteStrength;\n"
                                "    color *= clamp(vig, 0.0, 1.0);\n"
                                "    color = (color - 0.5) * uContrast + 0.5;\n"
                                "    float grey = dot(color, vec3(0.2126, 0.7152, 0.0722));\n"
                                "    color = mix(vec3(grey), color, uSaturation);\n"
                                "    fragColor = vec4(max(color, 0.0), 1.0);\n"
                                "}\n";

const char k_retro_frag_helpers[] =
    "in vec2 vTexCoord;\n"
    "uniform sampler2D uScene;\n"
    "uniform int uProfile;\n"
    "uniform vec2 uVirtualResolution;\n"
    "uniform vec2 uOutputResolution;\n"
    "out vec4 fragColor;\n"
    "float retroBayer4(vec2 p) {\n"
    "    int x = int(mod(p.x, 4.0));\n"
    "    int y = int(mod(p.y, 4.0));\n"
    "    int i = y * 4 + x;\n"
    "    float bayer[16] = float[16](0.0/16.0, 8.0/16.0, 2.0/16.0, 10.0/16.0,\n"
    "                                    12.0/16.0, 4.0/16.0, 14.0/16.0, 6.0/16.0,\n"
    "                                    3.0/16.0, 11.0/16.0, 1.0/16.0, 9.0/16.0,\n"
    "                                    15.0/16.0, 7.0/16.0, 13.0/16.0, 5.0/16.0);\n"
    "    return bayer[i];\n"
    "}\n"
    "vec3 retroGrade(vec3 color, float contrast, float saturation) {\n"
    "    color = (color - 0.5) * contrast + 0.5;\n"
    "    float lum = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "    return mix(vec3(lum), color, saturation);\n"
    "}\n"
    "vec2 retroNearestUV(vec2 uv, vec2 virtualResolution) {\n"
    "    vec2 res = max(virtualResolution, vec2(1.0));\n"
    "    return clamp((floor(uv * res) + vec2(0.5)) / res, vec2(0.0), vec2(1.0));\n"
    "}\n"
    "vec3 retroSampleNearest(vec2 uv, vec2 virtualResolution) {\n"
    "    return texture(uScene, retroNearestUV(uv, virtualResolution)).rgb;\n"
    "}\n"
    "vec3 retroSampleSoft(vec2 uv, vec2 virtualResolution) {\n"
    "    vec2 res = max(virtualResolution, vec2(1.0));\n"
    "    vec2 base = retroNearestUV(uv, res);\n"
    "    vec2 texel = 1.0 / res;\n"
    "    vec3 color = texture(uScene, base).rgb * 0.50;\n"
    "    color += texture(uScene, clamp(base + vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb * 0.125;\n"
    "    color += texture(uScene, clamp(base - vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb * 0.125;\n"
    "    color += texture(uScene, clamp(base + vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb * 0.125;\n"
    "    color += texture(uScene, clamp(base - vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb * 0.125;\n"
    "    return color;\n"
    "}\n"
    "vec3 retroQuantize(vec3 color, float levels, float dither) {\n"
    "    return floor(clamp(color + vec3(dither), vec3(0.0), vec3(1.0)) * levels + 0.5) / levels;\n"
    "}\n"
    "float retroVignette(vec2 uv, float strength) {\n"
    "    vec2 centered = uv * 2.0 - 1.0;\n"
    "    return clamp(1.0 - dot(centered, centered) * strength, 0.0, 1.0);\n"
    "}\n";

const char k_retro_frag_main[] =
    "void main() {\n"
    "    vec2 uv = vTexCoord;\n"
    "    vec2 outputCoord = vTexCoord * max(uOutputResolution, vec2(1.0));\n"
    "    vec3 color;\n"
    "    if (uProfile == 1) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(320.0, 240.0);\n"
    "        float row = floor(uv.y * res.y);\n"
    "        float jitter = (fract(sin(row * 12.9898) * 43758.5453) - 0.5) * 1.35 / res.x;\n"
    "        color = retroSampleNearest(vec2(clamp(uv.x + jitter, 0.0, 1.0), uv.y), res);\n"
    "        float dither = (retroBayer4(outputCoord) - 0.5) / 10.0;\n"
    "        color = retroQuantize(color, 31.0, dither);\n"
    "        color = retroGrade(color, 1.22, 0.82) * vec3(1.05, 0.98, 0.92);\n"
    "        color *= retroVignette(uv, 0.28);\n"
    "    } else if (uProfile == 2) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(320.0, 240.0);\n"
    "        color = retroSampleSoft(uv, res);\n"
    "        color = retroQuantize(color, 63.0, 0.0);\n"
    "        color = retroGrade(color * vec3(1.08, 1.03, 0.92), 1.08, 1.12);\n"
    "        color *= retroVignette(uv, 0.16);\n"
    "    } else if (uProfile == 3) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(320.0, 200.0);\n"
    "        color = retroSampleNearest(uv, res);\n"
    "        float dither = (retroBayer4(outputCoord) - 0.5) / 2.75;\n"
    "        color = retroQuantize(color, 5.0, dither);\n"
    "        color = retroGrade(color * vec3(1.13, 0.98, 0.82), 1.28, 0.72);\n"
    "        if (mod(outputCoord.y, 2.0) < 1.0) color *= 0.76;\n"
    "    } else if (uProfile == 4) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(256.0, 224.0);\n"
    "        color = retroSampleNearest(uv, res);\n"
    "        color = retroQuantize(color, 31.0, (retroBayer4(outputCoord) - 0.5) / 18.0);\n"
    "        color = retroGrade(color * vec3(0.90, 0.96, 1.14), 1.12, 1.18);\n"
    "        if (mod(outputCoord.y, 2.0) < 1.0) color *= 0.82;\n"
    "    } else if (uProfile == 5) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(512.0, 342.0);\n"
    "        color = retroSampleNearest(uv, res);\n"
    "        float lum = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "        float dither = (retroBayer4(outputCoord) - 0.5) / 3.0;\n"
    "        float grey = floor(clamp(lum + dither, 0.0, 1.0) * 3.0 + 0.5) / 3.0;\n"
    "        color = vec3(grey);\n"
    "        if (mod(outputCoord.y, 2.0) < 1.0) color *= 0.90;\n"
    "    } else if (uProfile == 6) {\n"
    "        vec2 res = (uVirtualResolution.x > 0.0 && uVirtualResolution.y > 0.0) ? "
    "uVirtualResolution : vec2(160.0, 144.0);\n"
    "        color = retroSampleNearest(uv, res);\n"
    "        float lum = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "        float dither = (retroBayer4(outputCoord) - 0.5) / 14.0;\n"
    "        float ramp = floor(clamp(pow(lum, 0.86) + dither, 0.0, 1.0) * 11.0 + 0.5) / 11.0;\n"
    "        vec3 shadow = vec3(0.045, 0.105, 0.045);\n"
    "        vec3 mid = vec3(0.360, 0.565, 0.190);\n"
    "        vec3 highlight = vec3(0.790, 0.880, 0.485);\n"
    "        color = mix(shadow, mid, smoothstep(0.0, 0.62, ramp));\n"
    "        color = mix(color, highlight, smoothstep(0.40, 1.0, ramp));\n"
    "        color = retroGrade(color, 1.08, 1.0);\n"
    "        if (mod(outputCoord.y, 2.0) < 1.0) color *= 0.92;\n"
    "    } else {\n"
    "        color = texture(uScene, uv).rgb;\n"
    "    }\n"
    "    fragColor = vec4(clamp(color, 0.0, 1.0), 1.0);\n"
    "}\n";

const char k_ssao_frag[] = "in vec2 vTexCoord;\n"
                           "uniform sampler2D uScene;\n"
                           "uniform sampler2D uDepth;\n"
                           "uniform vec2 uTexelSize;\n"
                           "uniform float uNear;\n"
                           "uniform float uFar;\n"
                           "out vec4 fragColor;\n"
                           "float linearizeDepth(float d) {\n"
                           "    float z = d * 2.0 - 1.0;\n"
                           "    return (2.0 * uNear * uFar) / (uFar + uNear - z * (uFar - uNear));\n"
                           "}\n"
                           "void main() {\n"
                           "    float rawDepth = texture(uDepth, vTexCoord).r;\n"
                           "    vec3 color = texture(uScene, vTexCoord).rgb;\n"
                           "    if (rawDepth > 0.999) { fragColor = vec4(color, 1.0); return; }\n"
                           "    float depth = linearizeDepth(rawDepth);\n"
                           "    /* Scattered sample offsets (avoids grid banding). */\n"
                           "    const vec2 offsets[8] = vec2[8](\n"
                           "        vec2(-0.94, -0.34), vec2( 0.76,  0.65),\n"
                           "        vec2(-0.09, -0.93), vec2( 0.97, -0.22),\n"
                           "        vec2(-0.71,  0.71), vec2( 0.33,  0.94),\n"
                           "        vec2( 0.52, -0.85), vec2(-0.86,  0.12)\n"
                           "    );\n"
                           "    float radius = clamp(1.0 / depth, 1.0, 8.0);\n"
                           "    float ao = 0.0;\n"
                           "    for (int i = 0; i < 8; i++) {\n"
                           "        vec2 sampleUV = vTexCoord + offsets[i] * uTexelSize * radius;\n"
                           "        float sd = linearizeDepth(texture(uDepth, sampleUV).r);\n"
                           "        float diff = depth - sd;\n"
                           "        if (diff > 0.1 && diff < 2.0) ao += 1.0;\n"
                           "    }\n"
                           "    ao /= 8.0;\n"
                           "    color *= (1.0 - ao * 0.35);\n"
                           "    fragColor = vec4(color, 1.0);\n"
                           "}\n";

/* ------------------------------------------------------------------ */
/* IBL shader sources                                                  */
/* ------------------------------------------------------------------ */

const char k_cube_vert[] = "layout(location = 0) in vec3 aPosition;\n"
                           "out vec3 vLocalPos;\n"
                           "uniform mat4 uProjection;\n"
                           "uniform mat4 uView;\n"
                           "void main() {\n"
                           "    vLocalPos = aPosition;\n"
                           "    gl_Position = uProjection * uView * vec4(aPosition, 1.0);\n"
                           "}\n";

const char k_equirect_to_cube_frag[] = "in vec3 vLocalPos;\n"
                                       "out vec4 fragColor;\n"
                                       "uniform sampler2D uEquirectMap;\n"
                                       "const vec2 invAtan = vec2(0.1591, 0.3183);\n"
                                       "void main() {\n"
                                       "    vec3 d = normalize(vLocalPos);\n"
                                       "    vec2 uv = vec2(atan(d.z, d.x), asin(d.y));\n"
                                       "    uv *= invAtan;\n"
                                       "    uv += 0.5;\n"
                                       "    vec3 color = texture(uEquirectMap, uv).rgb;\n"
                                       "    fragColor = vec4(color, 1.0);\n"
                                       "}\n";

const char k_irradiance_frag[] =
    "in vec3 vLocalPos;\n"
    "out vec4 fragColor;\n"
    "uniform samplerCube uEnvironmentMap;\n"
    "const float PI = 3.14159265;\n"
    "void main() {\n"
    "    vec3 N = normalize(vLocalPos);\n"
    "    vec3 irradiance = vec3(0.0);\n"
    "    vec3 up = vec3(0.0, 1.0, 0.0);\n"
    "    vec3 right = normalize(cross(up, N));\n"
    "    up = normalize(cross(N, right));\n"
    "    float sampleDelta = 0.025;\n"
    "    float nrSamples = 0.0;\n"
    "    for (float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta) {\n"
    "        for (float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta) {\n"
    "            vec3 tangentSample = vec3(sin(theta)*cos(phi), sin(theta)*sin(phi), cos(theta));\n"
    "            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;\n"
    "            irradiance += texture(uEnvironmentMap, sampleVec).rgb * cos(theta) * sin(theta);\n"
    "            nrSamples++;\n"
    "        }\n"
    "    }\n"
    "    irradiance = PI * irradiance * (1.0 / nrSamples);\n"
    "    fragColor = vec4(irradiance, 1.0);\n"
    "}\n";

const char k_prefilter_frag[] = "in vec3 vLocalPos;\n"
                                "out vec4 fragColor;\n"
                                "uniform samplerCube uEnvironmentMap;\n"
                                "uniform float uRoughness;\n"
                                "const float PI = 3.14159265;\n"
                                "float RadicalInverse_VdC(uint bits) {\n"
                                "    bits = (bits << 16u) | (bits >> 16u);\n"
                                "    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);\n"
                                "    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);\n"
                                "    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);\n"
                                "    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);\n"
                                "    return float(bits) * 2.3283064365386963e-10;\n"
                                "}\n"
                                "vec2 Hammersley(uint i, uint N) {\n"
                                "    return vec2(float(i)/float(N), RadicalInverse_VdC(i));\n"
                                "}\n"
                                "vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float roughness) {\n"
                                "    float a = roughness * roughness;\n"
                                "    float phi = 2.0 * PI * Xi.x;\n"
                                "    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));\n"
                                "    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);\n"
                                "    vec3 H = vec3(cos(phi)*sinTheta, sin(phi)*sinTheta, cosTheta);\n"
                                "    vec3 up = abs(N.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);\n"
                                "    vec3 tangent = normalize(cross(up, N));\n"
                                "    vec3 bitangent = cross(N, tangent);\n"
                                "    return tangent * H.x + bitangent * H.y + N * H.z;\n"
                                "}\n"
                                "void main() {\n"
                                "    vec3 N = normalize(vLocalPos);\n"
                                "    vec3 R = N;\n"
                                "    vec3 V = R;\n"
                                "    const uint SAMPLE_COUNT = 1024u;\n"
                                "    float totalWeight = 0.0;\n"
                                "    vec3 prefilteredColor = vec3(0.0);\n"
                                "    for (uint i = 0u; i < SAMPLE_COUNT; ++i) {\n"
                                "        vec2 Xi = Hammersley(i, SAMPLE_COUNT);\n"
                                "        vec3 H = ImportanceSampleGGX(Xi, N, uRoughness);\n"
                                "        vec3 L = normalize(2.0 * dot(V, H) * H - V);\n"
                                "        float NdotL = max(dot(N, L), 0.0);\n"
                                "        if (NdotL > 0.0) {\n"
                                "            prefilteredColor += texture(uEnvironmentMap, L).rgb * NdotL;\n"
                                "            totalWeight += NdotL;\n"
                                "        }\n"
                                "    }\n"
                                "    prefilteredColor /= totalWeight;\n"
                                "    fragColor = vec4(prefilteredColor, 1.0);\n"
                                "}\n";

const char k_brdf_vert[] = "layout(location = 0) in vec3 aPosition;\n"
                           "layout(location = 2) in vec2 aTexCoord;\n"
                           "out vec2 vTexCoord;\n"
                           "void main() {\n"
                           "    vTexCoord = aTexCoord;\n"
                           "    gl_Position = vec4(aPosition, 1.0);\n"
                           "}\n";

const char k_brdf_frag[] = "in vec2 vTexCoord;\n"
                           "out vec4 fragColor;\n"
                           "const float PI = 3.14159265;\n"
                           "float RadicalInverse_VdC(uint bits) {\n"
                           "    bits = (bits << 16u) | (bits >> 16u);\n"
                           "    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);\n"
                           "    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);\n"
                           "    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);\n"
                           "    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);\n"
                           "    return float(bits) * 2.3283064365386963e-10;\n"
                           "}\n"
                           "vec2 Hammersley(uint i, uint N) {\n"
                           "    return vec2(float(i)/float(N), RadicalInverse_VdC(i));\n"
                           "}\n"
                           "vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float roughness) {\n"
                           "    float a = roughness * roughness;\n"
                           "    float phi = 2.0 * PI * Xi.x;\n"
                           "    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));\n"
                           "    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);\n"
                           "    vec3 H = vec3(cos(phi)*sinTheta, sin(phi)*sinTheta, cosTheta);\n"
                           "    vec3 up = abs(N.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);\n"
                           "    vec3 tangent = normalize(cross(up, N));\n"
                           "    vec3 bitangent = cross(N, tangent);\n"
                           "    return tangent * H.x + bitangent * H.y + N * H.z;\n"
                           "}\n"
                           "float GeometrySchlickGGX(float NdotV, float roughness) {\n"
                           "    float a = roughness;\n"
                           "    float k = (a * a) / 2.0;\n"
                           "    return NdotV / (NdotV * (1.0 - k) + k);\n"
                           "}\n"
                           "float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness) {\n"
                           "    float NdotV = max(dot(N, V), 0.0);\n"
                           "    float NdotL = max(dot(N, L), 0.0);\n"
                           "    return GeometrySchlickGGX(NdotV, roughness) * GeometrySchlickGGX(NdotL, roughness);\n"
                           "}\n"
                           "vec2 IntegrateBRDF(float NdotV, float roughness) {\n"
                           "    vec3 V = vec3(sqrt(1.0 - NdotV*NdotV), 0.0, NdotV);\n"
                           "    float A = 0.0;\n"
                           "    float B = 0.0;\n"
                           "    vec3 N = vec3(0.0, 0.0, 1.0);\n"
                           "    const uint SAMPLE_COUNT = 1024u;\n"
                           "    for (uint i = 0u; i < SAMPLE_COUNT; ++i) {\n"
                           "        vec2 Xi = Hammersley(i, SAMPLE_COUNT);\n"
                           "        vec3 H = ImportanceSampleGGX(Xi, N, roughness);\n"
                           "        vec3 L = normalize(2.0 * dot(V, H) * H - V);\n"
                           "        float NdotL = max(L.z, 0.0);\n"
                           "        float NdotH = max(H.z, 0.0);\n"
                           "        float VdotH = max(dot(V, H), 0.0);\n"
                           "        if (NdotL > 0.0) {\n"
                           "            float G = GeometrySmith(N, V, L, roughness);\n"
                           "            float G_Vis = (G * VdotH) / (NdotH * NdotV);\n"
                           "            float Fc = pow(1.0 - VdotH, 5.0);\n"
                           "            A += (1.0 - Fc) * G_Vis;\n"
                           "            B += Fc * G_Vis;\n"
                           "        }\n"
                           "    }\n"
                           "    A /= float(SAMPLE_COUNT);\n"
                           "    B /= float(SAMPLE_COUNT);\n"
                           "    return vec2(A, B);\n"
                           "}\n"
                           "void main() {\n"
                           "    vec2 integratedBRDF = IntegrateBRDF(vTexCoord.x, vTexCoord.y);\n"
                           "    fragColor = vec4(integratedBRDF, 0.0, 1.0);\n"
                           "}\n";

/* Unit cube vertices for cubemap rendering. */
