/*
 * Embedded GLSL shader source strings for the OpenGL backend.
 * Two variants: GLSL 330 (desktop) and GLSL ES 300 (mobile/web).
 */

#ifndef SDL3D_GL_SHADERS_H
#define SDL3D_GL_SHADERS_H

#ifdef SDL3D_OPENGL_ES
#define SDL3D_GLSL_VERSION "#version 300 es\nprecision highp float;\n"
#else
#define SDL3D_GLSL_VERSION "#version 330\n"
#endif

/* ================================================================== */
/* Unlit shader: texture × vertex color × tint                        */
/* ================================================================== */

static const char *sdl3d_shader_unlit_vert = SDL3D_GLSL_VERSION "in vec3 aPosition;\n"
                                                                "in vec2 aTexCoord;\n"
                                                                "in vec4 aColor;\n"
                                                                "uniform mat4 uMVP;\n"
                                                                "out vec2 vTexCoord;\n"
                                                                "out vec4 vColor;\n"
                                                                "void main() {\n"
                                                                "    vTexCoord = aTexCoord;\n"
                                                                "    vColor = aColor;\n"
                                                                "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
                                                                "}\n";

static const char *sdl3d_shader_unlit_frag =
    SDL3D_GLSL_VERSION "in vec2 vTexCoord;\n"
                       "in vec4 vColor;\n"
                       "uniform sampler2D uTexture;\n"
                       "uniform vec4 uTint;\n"
                       "uniform int uHasTexture;\n"
                       "out vec4 fragColor;\n"
                       "void main() {\n"
                       "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, vTexCoord) : vec4(1.0);\n"
                       "    fragColor = texel * vColor * uTint;\n"
                       "    if (fragColor.a <= 0.0) discard;\n"
                       "}\n";

/* ================================================================== */
/* PBR lit shader: Cook-Torrance with lights, fog, tonemapping        */
/* ================================================================== */

static const char *sdl3d_shader_lit_vert = SDL3D_GLSL_VERSION "in vec3 aPosition;\n"
                                                              "in vec3 aNormal;\n"
                                                              "in vec2 aTexCoord;\n"
                                                              "in vec4 aColor;\n"
                                                              "uniform mat4 uMVP;\n"
                                                              "uniform mat4 uModel;\n"
                                                              "uniform mat3 uNormalMatrix;\n"
                                                              "out vec3 vWorldPos;\n"
                                                              "out vec3 vWorldNormal;\n"
                                                              "out vec2 vTexCoord;\n"
                                                              "out vec4 vColor;\n"
                                                              "void main() {\n"
                                                              "    vec4 worldPos = uModel * vec4(aPosition, 1.0);\n"
                                                              "    vWorldPos = worldPos.xyz;\n"
                                                              "    vWorldNormal = normalize(uNormalMatrix * aNormal);\n"
                                                              "    vTexCoord = aTexCoord;\n"
                                                              "    vColor = aColor;\n"
                                                              "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
                                                              "}\n";

static const char *sdl3d_shader_lit_frag = SDL3D_GLSL_VERSION
    "#define MAX_LIGHTS 8\n"
    "#define PI 3.14159265\n"
    "\n"
    "struct Light {\n"
    "    int type;\n" /* 0=dir, 1=point, 2=spot */
    "    vec3 position;\n"
    "    vec3 direction;\n"
    "    vec3 color;\n"
    "    float intensity;\n"
    "    float range;\n"
    "    float innerCutoff;\n"
    "    float outerCutoff;\n"
    "};\n"
    "\n"
    "in vec3 vWorldPos;\n"
    "in vec3 vWorldNormal;\n"
    "in vec2 vTexCoord;\n"
    "in vec4 vColor;\n"
    "\n"
    "uniform sampler2D uTexture;\n"
    "uniform int uHasTexture;\n"
    "uniform vec4 uTint;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform float uMetallic;\n"
    "uniform float uRoughness;\n"
    "uniform vec3 uEmissive;\n"
    "uniform int uLightCount;\n"
    "uniform Light uLights[MAX_LIGHTS];\n"
    "uniform int uTonemapMode;\n"
    "uniform int uFogMode;\n"
    "uniform vec3 uFogColor;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "\n"
    "out vec4 fragColor;\n"
    "\n"
    "float DistributionGGX(float NdotH, float r) {\n"
    "    float a = r * r;\n"
    "    float a2 = a * a;\n"
    "    float d = NdotH * NdotH * (a2 - 1.0) + 1.0;\n"
    "    return a2 / (PI * d * d + 0.0001);\n"
    "}\n"
    "float GeometrySchlickGGX(float NdotV, float r) {\n"
    "    float k = (r + 1.0) * (r + 1.0) / 8.0;\n"
    "    return NdotV / (NdotV * (1.0 - k) + k + 0.0001);\n"
    "}\n"
    "vec3 FresnelSchlick(float cosTheta, vec3 F0) {\n"
    "    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, vTexCoord) : vec4(1.0);\n"
    "    vec3 albedo = texel.rgb * vColor.rgb * uTint.rgb;\n"
    "    float alpha = texel.a * vColor.a * uTint.a;\n"
    "    if (alpha <= 0.0) discard;\n"
    "\n"
    "    vec3 N = normalize(vWorldNormal);\n"
    "    vec3 V = normalize(uCameraPos - vWorldPos);\n"
    "    float NdotV = max(dot(N, V), 0.0);\n"
    "    vec3 F0 = mix(vec3(0.04), albedo, uMetallic);\n"
    "\n"
    "    vec3 Lo = vec3(0.0);\n"
    "    for (int i = 0; i < uLightCount; i++) {\n"
    "        vec3 L; float attenuation = 1.0;\n"
    "        if (uLights[i].type == 0) {\n"
    "            L = normalize(-uLights[i].direction);\n"
    "        } else {\n"
    "            vec3 toLight = uLights[i].position - vWorldPos;\n"
    "            float dist = length(toLight);\n"
    "            L = toLight / dist;\n"
    "            if (uLights[i].range > 0.0) {\n"
    "                float r = dist / uLights[i].range;\n"
    "                attenuation = max(1.0 - r * r, 0.0);\n"
    "                attenuation *= attenuation;\n"
    "            }\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                attenuation *= clamp((cosA - uLights[i].outerCutoff) / max(eps, 0.0001), 0.0, 1.0);\n"
    "            }\n"
    "        }\n"
    "        vec3 radiance = uLights[i].color * uLights[i].intensity * attenuation;\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        if (NdotL <= 0.0) continue;\n"
    "        vec3 H = normalize(L + V);\n"
    "        float NdotH = max(dot(N, H), 0.0);\n"
    "        float HdotV = max(dot(H, V), 0.0);\n"
    "        float NDF = DistributionGGX(NdotH, uRoughness);\n"
    "        float G = GeometrySchlickGGX(NdotV, uRoughness) * GeometrySchlickGGX(NdotL, uRoughness);\n"
    "        vec3 F = FresnelSchlick(HdotV, F0);\n"
    "        vec3 spec = (NDF * G * F) / (4.0 * NdotV * NdotL + 0.0001);\n"
    "        vec3 kD = (1.0 - F) * (1.0 - uMetallic);\n"
    "        vec3 diff = kD * albedo / PI;\n"
    "        Lo += (diff + spec) * radiance * NdotL;\n"
    "    }\n"
    "\n"
    "    vec3 color = uAmbient * albedo + Lo + uEmissive;\n"
    "\n"
    "    /* Fog. */\n"
    "    if (uFogMode > 0) {\n"
    "        float dist = length(uCameraPos - vWorldPos);\n"
    "        float fogFactor = 0.0;\n"
    "        if (uFogMode == 1) fogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "        else if (uFogMode == 2) fogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "        else if (uFogMode == 3) { float d = uFogDensity * dist; fogFactor = 1.0 - exp(-d * d); }\n"
    "        color = mix(color, uFogColor, fogFactor);\n"
    "    }\n"
    "\n"
    "    /* Tonemapping. */\n"
    "    if (uTonemapMode == 1) color = color / (1.0 + color);\n"
    "    else if (uTonemapMode == 2) {\n"
    "        float a=2.51, b=0.03, c=2.43, d=0.59, e=0.14;\n"
    "        color = clamp((color*(a*color+b))/(color*(c*color+d)+e), 0.0, 1.0);\n"
    "    }\n"
    "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
    "\n"
    "    fragColor = vec4(color, alpha);\n"
    "}\n";

#endif
