/*
 * Embedded GLSL shader source strings for the OpenGL backend.
 * Two variants: GLSL 330 (desktop) and GLSL ES 300 (mobile/web).
 */

#ifndef SDL3D_GL_SHADERS_H
#define SDL3D_GL_SHADERS_H

#ifdef SDL3D_OPENGL_ES
#define SDL3D_GLSL_VERSION "#version 300 es\nprecision highp float;\n"
#else
#define SDL3D_GLSL_VERSION ""
#endif

/* Runtime version prefix — selected based on actual GL context type. */
#define SDL3D_GLSL_VERSION_330 "#version 330\n"
#define SDL3D_GLSL_VERSION_ES300 "#version 300 es\nprecision highp float;\n"

/* ================================================================== */
/* Unlit shader: texture × vertex color × tint                        */
/* ================================================================== */

static const char *sdl3d_shader_unlit_vert = SDL3D_GLSL_VERSION "layout(location = 0) in vec3 aPosition;\n"
                                                                "layout(location = 1) in vec2 aTexCoord;\n"
                                                                "layout(location = 2) in vec4 aColor;\n"
                                                                "uniform mat4 uMVP;\n"
                                                                "out vec2 vTexCoord;\n"
                                                                "out vec4 vColor;\n"
                                                                "void main() {\n"
                                                                "    vTexCoord = aTexCoord;\n"
                                                                "    vColor = aColor;\n"
                                                                "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
                                                                "}\n";

static const char *sdl3d_shader_unlit_frag =
    SDL3D_GLSL_VERSION "in vec2 vTexCoord;\n"
                       "in vec4 vColor;\n"
                       "uniform sampler2D uTexture;\n"
                       "uniform vec4 uTint;\n"
                       "uniform int uHasTexture;\n"
                       "out vec4 fragColor;\n"
                       "void main() {\n"
                       "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
                       "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
                       "    fragColor = texel * vColor * uTint;\n"
                       "    if (fragColor.a <= 0.0) discard;\n"
                       "}\n";

/* ================================================================== */
/* PBR lit shader: Cook-Torrance with lights, fog, tonemapping        */
/* ================================================================== */

static const char *sdl3d_shader_lit_vert =
    SDL3D_GLSL_VERSION "layout(location = 0) in vec3 aPosition;\n"
                       "layout(location = 1) in vec3 aNormal;\n"
                       "layout(location = 2) in vec2 aTexCoord;\n"
                       "layout(location = 3) in vec4 aColor;\n"
                       "layout(location = 4) in vec4 aJointIndices;\n"
                       "layout(location = 5) in vec4 aJointWeights;\n"
                       "uniform mat4 uMVP;\n"
                       "uniform mat4 uModel;\n"
                       "uniform mat3 uNormalMatrix;\n"
                       "uniform int uSkinned;\n"
                       "uniform mat4 uJointMatrices[64];\n"
                       "out vec3 vWorldPos;\n"
                       "out vec3 vWorldNormal;\n"
                       "out vec2 vTexCoord;\n"
                       "out vec4 vColor;\n"
                       "void main() {\n"
                       "    vec3 pos = aPosition;\n"
                       "    vec3 norm = aNormal;\n"
                       "    if (uSkinned != 0) {\n"
                       "        mat4 skin = uJointMatrices[int(aJointIndices.x)] * aJointWeights.x\n"
                       "                  + uJointMatrices[int(aJointIndices.y)] * aJointWeights.y\n"
                       "                  + uJointMatrices[int(aJointIndices.z)] * aJointWeights.z\n"
                       "                  + uJointMatrices[int(aJointIndices.w)] * aJointWeights.w;\n"
                       "        pos = (skin * vec4(aPosition, 1.0)).xyz;\n"
                       "        norm = mat3(skin) * aNormal;\n"
                       "    }\n"
                       "    vec4 worldPos = uModel * vec4(pos, 1.0);\n"
                       "    vWorldPos = worldPos.xyz;\n"
                       "    vWorldNormal = normalize(uNormalMatrix * norm);\n"
                       "    vTexCoord = aTexCoord;\n"
                       "    vColor = aColor;\n"
                       "    gl_Position = uMVP * vec4(pos, 1.0);\n"
                       "}\n";

#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif
static const char *sdl3d_shader_lit_frag = SDL3D_GLSL_VERSION
    "#define MAX_LIGHTS 8\n"
    "#define PI 3.14159265\n"
    "\n"
    "struct Light {\n"
    "    int type;\n" /* 0=dir, 1=point, 2=spot */
    "    vec3 position;\n"
    "    vec3 direction;\n"
    "    vec3 color;\n"
    "    float intensity;\n"
    "    float range;\n"
    "    float innerCutoff;\n"
    "    float outerCutoff;\n"
    "};\n"
    "\n"
    "in vec3 vWorldPos;\n"
    "in vec3 vWorldNormal;\n"
    "in vec2 vTexCoord;\n"
    "in vec4 vColor;\n"
    "\n"
    "uniform sampler2D uTexture;\n"
    "uniform int uHasTexture;\n"
    "uniform vec4 uTint;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform float uMetallic;\n"
    "uniform float uRoughness;\n"
    "uniform vec3 uEmissive;\n"
    "uniform int uLightCount;\n"
    "uniform Light uLights[MAX_LIGHTS];\n"
    "uniform int uTonemapMode;\n"
    "uniform int uFogMode;\n"
    "uniform vec3 uFogColor;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "uniform sampler2D uShadowMap;\n"
    "uniform mat4 uShadowVP;\n"
    "uniform int uShadowEnabled;\n"
    "uniform float uShadowBias;\n"
    "\n"
    "out vec4 fragColor;\n"
    "\n"
    "float DistributionGGX(float NdotH, float r) {\n"
    "    float a = r * r;\n"
    "    float a2 = a * a;\n"
    "    float d = NdotH * NdotH * (a2 - 1.0) + 1.0;\n"
    "    return a2 / (PI * d * d + 0.0001);\n"
    "}\n"
    "float GeometrySchlickGGX(float NdotV, float r) {\n"
    "    float k = (r + 1.0) * (r + 1.0) / 8.0;\n"
    "    return NdotV / (NdotV * (1.0 - k) + k + 0.0001);\n"
    "}\n"
    "vec3 FresnelSchlick(float cosTheta, vec3 F0) {\n"
    "    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
    "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
    "    vec3 albedo = texel.rgb * vColor.rgb * uTint.rgb;\n"
    "    float alpha = texel.a * vColor.a * uTint.a;\n"
    "    if (alpha <= 0.0) discard;\n"
    "\n"
    "    vec3 N = normalize(vWorldNormal);\n"
    "    vec3 V = normalize(uCameraPos - vWorldPos);\n"
    "    float NdotV = max(dot(N, V), 0.0);\n"
    "    vec3 F0 = mix(vec3(0.04), albedo, uMetallic);\n"
    "\n"
    "    vec3 Lo = vec3(0.0);\n"
    "    for (int i = 0; i < uLightCount; i++) {\n"
    "        vec3 L; float attenuation = 1.0;\n"
    "        if (uLights[i].type == 0) {\n"
    "            L = normalize(-uLights[i].direction);\n"
    "        } else {\n"
    "            vec3 toLight = uLights[i].position - vWorldPos;\n"
    "            float dist = length(toLight);\n"
    "            L = toLight / dist;\n"
    "            if (uLights[i].range > 0.0) {\n"
    "                float r = dist / uLights[i].range;\n"
    "                attenuation = max(1.0 - r * r, 0.0);\n"
    "                attenuation *= attenuation;\n"
    "            }\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                attenuation *= clamp((cosA - uLights[i].outerCutoff) / max(eps, 0.0001), 0.0, 1.0);\n"
    "            }\n"
    "        }\n"
    "        vec3 radiance = uLights[i].color * uLights[i].intensity * attenuation;\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        if (NdotL <= 0.0) continue;\n"
    "        vec3 H = normalize(L + V);\n"
    "        float NdotH = max(dot(N, H), 0.0);\n"
    "        float HdotV = max(dot(H, V), 0.0);\n"
    "        float NDF = DistributionGGX(NdotH, uRoughness);\n"
    "        float G = GeometrySchlickGGX(NdotV, uRoughness) * GeometrySchlickGGX(NdotL, uRoughness);\n"
    "        vec3 F = FresnelSchlick(HdotV, F0);\n"
    "        vec3 spec = (NDF * G * F) / (4.0 * NdotV * NdotL + 0.0001);\n"
    "        vec3 kD = (1.0 - F) * (1.0 - uMetallic);\n"
    "        vec3 diff = kD * albedo / PI;\n"
    "        Lo += (diff + spec) * radiance * NdotL;\n"
    "    }\n"
    "\n"
    "    /* Shadow map sampling for directional light (light 0). */\n"
    "    if (uShadowEnabled != 0) {\n"
    "        vec4 lpos = uShadowVP * vec4(vWorldPos, 1.0);\n"
    "        vec3 sndc = lpos.xyz / lpos.w;\n"
    "        vec2 suv = sndc.xy * 0.5 + 0.5;\n"
    "        if (suv.x >= 0.0 && suv.x <= 1.0 && suv.y >= 0.0 && suv.y <= 1.0) {\n"
    "            float closest = texture(uShadowMap, suv).r;\n"
    "            float current = sndc.z * 0.5 + 0.5;\n"
    "            if (current - uShadowBias > closest) Lo = vec3(0.0);\n"
    "        }\n"
    "    }\n"
    "    vec3 color = uAmbient * albedo + Lo + uEmissive;\n"
    "\n"
    "    /* Fog. */\n"
    "    if (uFogMode > 0) {\n"
    "        float dist = length(uCameraPos - vWorldPos);\n"
    "        float fogFactor = 0.0;\n"
    "        if (uFogMode == 1) fogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "        else if (uFogMode == 2) fogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "        else if (uFogMode == 3) { float d = uFogDensity * dist; fogFactor = 1.0 - exp(-d * d); }\n"
    "        color = mix(color, uFogColor, fogFactor);\n"
    "    }\n"
    "\n"
    "    /* Tonemapping. */\n"
    "    if (uTonemapMode == 1) color = color / (1.0 + color);\n"
    "    else if (uTonemapMode == 2) {\n"
    "        float a=2.51, b=0.03, c=2.43, d=0.59, e=0.14;\n"
    "        color = clamp((color*(a*color+b))/(color*(c*color+d)+e), 0.0, 1.0);\n"
    "    }\n"
    "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
    "\n"
    "    fragColor = vec4(color, alpha);\n"
    "}\n";
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif

/* ================================================================== */
/* PS1 shader: vertex snap + affine UVs + Gouraud + dither            */
/* ================================================================== */

static const char *sdl3d_shader_ps1_vert =
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aTexCoord;\n"
    "layout(location = 3) in vec4 aColor;\n"
    "uniform mat4 uMVP;\n"
    "uniform mat4 uModel;\n"
    "uniform mat3 uNormalMatrix;\n"
    "uniform int uSnapPrecision;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform int uLightCount;\n"
    "struct Light { int type; vec3 position; vec3 direction; vec3 color;\n"
    "    float intensity; float range; float innerCutoff; float outerCutoff; };\n"
    "uniform Light uLights[8];\n"
    "uniform int uFogMode;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "noperspective out vec2 vTexCoord;\n"
    "out vec4 vColor;\n"
    "out float vFogFactor;\n"
    "void main() {\n"
    "    vec4 clipPos = uMVP * vec4(aPosition, 1.0);\n"
    "    float prec = float(uSnapPrecision > 0 ? uSnapPrecision : 1);\n"
    "    clipPos.xy = floor(clipPos.xy / clipPos.w * 120.0 / prec + 0.5) * prec / 120.0 * clipPos.w;\n"
    "    gl_Position = clipPos;\n"
    "    vTexCoord = aTexCoord;\n"
    "    /* Per-vertex Gouraud diffuse lighting. */\n"
    "    vec3 worldPos = (uModel * vec4(aPosition, 1.0)).xyz;\n"
    "    vec3 N = normalize(uNormalMatrix * aNormal);\n"
    "    vec3 lit = uAmbient;\n"
    "    for (int i = 0; i < uLightCount && i < 8; ++i) {\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (uLights[i].type == 0) { L = -normalize(uLights[i].direction); }\n"
    "        else { vec3 toLight = uLights[i].position - worldPos;\n"
    "            float d = length(toLight);\n"
    "            L = toLight / max(d, 0.0001);\n"
    "            if (uLights[i].range > 0.0) { float r = d / uLights[i].range; atten = max(1.0 - r * r, 0.0); atten *= "
    "atten; }\n"
    "            else atten = 1.0 / (d * d + 0.0001);\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                atten *= (abs(eps) < 0.0001) ? float(cosA >= uLights[i].outerCutoff)\n"
    "                                             : clamp((cosA - uLights[i].outerCutoff) / eps, 0.0, 1.0);\n"
    "            } }\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        lit += uLights[i].color * uLights[i].intensity * NdotL * atten;\n"
    "    }\n"
    "    vColor = vec4(min(lit, 1.0) * aColor.rgb, aColor.a);\n"
    "    /* Vertex fog. */\n"
    "    float dist = length(uCameraPos - worldPos);\n"
    "    vFogFactor = 0.0;\n"
    "    if (uFogMode == 1) vFogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "    else if (uFogMode == 2) vFogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "    else if (uFogMode == 3) { float d = uFogDensity * dist; vFogFactor = 1.0 - exp(-d * d); }\n"
    "}\n";

static const char *sdl3d_shader_ps1_frag =
    "noperspective in vec2 vTexCoord;\n"
    "in vec4 vColor;\n"
    "in float vFogFactor;\n"
    "uniform sampler2D uTexture;\n"
    "uniform int uHasTexture;\n"
    "uniform vec4 uTint;\n"
    "uniform vec3 uFogColor;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
    "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
    "    vec3 color = texel.rgb * vColor.rgb * uTint.rgb;\n"
    "    float alpha = texel.a * vColor.a * uTint.a;\n"
    "    if (alpha <= 0.0) discard;\n"
    "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
    "    color = mix(color, uFogColor, vFogFactor);\n"
    "    /* PS1: aggressive 4x4 Bayer dither + 5-bit (32-level) quantize. */\n"
    "    float bayer[16] = float[16](0.0/16.0, 8.0/16.0, 2.0/16.0, 10.0/16.0,\n"
    "                                12.0/16.0, 4.0/16.0, 14.0/16.0, 6.0/16.0,\n"
    "                                3.0/16.0, 11.0/16.0, 1.0/16.0, 9.0/16.0,\n"
    "                                15.0/16.0, 7.0/16.0, 13.0/16.0, 5.0/16.0);\n"
    "    ivec2 px = ivec2(gl_FragCoord.xy);\n"
    "    float dither = (bayer[(px.y % 4) * 4 + (px.x % 4)] - 0.5) / 24.0;\n"
    "    color = floor((color + dither) * 32.0 + 0.5) / 32.0;\n"
    "    /* Slight color desaturation — PS1 had limited color precision. */\n"
    "    float lum = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "    color = mix(vec3(lum), color, 0.85);\n"
    "    fragColor = vec4(max(color, 0.0), alpha);\n"
    "}\n";

/* ================================================================== */
/* N64 shader: Gouraud + bilinear + vertex fog (no quantization)      */
/* ================================================================== */

static const char *sdl3d_shader_n64_vert =
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aTexCoord;\n"
    "layout(location = 3) in vec4 aColor;\n"
    "uniform mat4 uMVP;\n"
    "uniform mat4 uModel;\n"
    "uniform mat3 uNormalMatrix;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform int uLightCount;\n"
    "struct Light { int type; vec3 position; vec3 direction; vec3 color;\n"
    "    float intensity; float range; float innerCutoff; float outerCutoff; };\n"
    "uniform Light uLights[8];\n"
    "uniform int uFogMode;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "out vec2 vTexCoord;\n"
    "out vec4 vColor;\n"
    "out float vFogFactor;\n"
    "void main() {\n"
    "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
    "    vTexCoord = aTexCoord;\n"
    "    vec3 worldPos = (uModel * vec4(aPosition, 1.0)).xyz;\n"
    "    vec3 N = normalize(uNormalMatrix * aNormal);\n"
    "    vec3 lit = uAmbient;\n"
    "    for (int i = 0; i < uLightCount && i < 8; ++i) {\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (uLights[i].type == 0) { L = -normalize(uLights[i].direction); }\n"
    "        else { vec3 toLight = uLights[i].position - worldPos;\n"
    "            float d = length(toLight);\n"
    "            L = toLight / max(d, 0.0001);\n"
    "            if (uLights[i].range > 0.0) { float r = d / uLights[i].range; atten = max(1.0 - r * r, 0.0); atten *= "
    "atten; }\n"
    "            else atten = 1.0 / (d * d + 0.0001);\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                atten *= (abs(eps) < 0.0001) ? float(cosA >= uLights[i].outerCutoff)\n"
    "                                             : clamp((cosA - uLights[i].outerCutoff) / eps, 0.0, 1.0);\n"
    "            } }\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        lit += uLights[i].color * uLights[i].intensity * NdotL * atten;\n"
    "    }\n"
    "    vColor = vec4(min(lit, 1.0) * aColor.rgb, aColor.a);\n"
    "    float dist = length(uCameraPos - worldPos);\n"
    "    vFogFactor = 0.0;\n"
    "    if (uFogMode == 1) vFogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "    else if (uFogMode == 2) vFogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "    else if (uFogMode == 3) { float d = uFogDensity * dist; vFogFactor = 1.0 - exp(-d * d); }\n"
    "}\n";

static const char *sdl3d_shader_n64_frag = "in vec2 vTexCoord;\n"
                                           "in vec4 vColor;\n"
                                           "in float vFogFactor;\n"
                                           "uniform sampler2D uTexture;\n"
                                           "uniform int uHasTexture;\n"
                                           "uniform vec4 uTint;\n"
                                           "uniform vec3 uFogColor;\n"
                                           "out vec4 fragColor;\n"
                                           "void main() {\n"
                                           "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
                                           "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
                                           "    vec3 color = texel.rgb * vColor.rgb * uTint.rgb;\n"
                                           "    float alpha = texel.a * vColor.a * uTint.a;\n"
                                           "    if (alpha <= 0.0) discard;\n"
                                           "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
                                           "    color = mix(color, uFogColor, vFogFactor);\n"
                                           "    /* N64: slight warm tint + soft contrast. */\n"
                                           "    color *= vec3(1.02, 1.0, 0.95);\n"
                                           "    color = clamp((color - 0.5) * 1.05 + 0.5, 0.0, 1.0);\n"
                                           "    fragColor = vec4(color, alpha);\n"
                                           "}\n";

/* ================================================================== */
/* DOS shader: affine + Gouraud + 6-level quantize + Bayer dither     */
/* ================================================================== */

static const char *sdl3d_shader_dos_vert =
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aTexCoord;\n"
    "layout(location = 3) in vec4 aColor;\n"
    "uniform mat4 uMVP;\n"
    "uniform mat4 uModel;\n"
    "uniform mat3 uNormalMatrix;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform int uLightCount;\n"
    "struct Light { int type; vec3 position; vec3 direction; vec3 color;\n"
    "    float intensity; float range; float innerCutoff; float outerCutoff; };\n"
    "uniform Light uLights[8];\n"
    "uniform int uFogMode;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "noperspective out vec2 vTexCoord;\n"
    "flat out vec4 vColor;\n"
    "out float vFogFactor;\n"
    "void main() {\n"
    "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
    "    vTexCoord = aTexCoord;\n"
    "    vec3 worldPos = (uModel * vec4(aPosition, 1.0)).xyz;\n"
    "    vec3 N = normalize(uNormalMatrix * aNormal);\n"
    "    vec3 lit = uAmbient;\n"
    "    for (int i = 0; i < uLightCount && i < 8; ++i) {\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (uLights[i].type == 0) { L = -normalize(uLights[i].direction); }\n"
    "        else { vec3 toLight = uLights[i].position - worldPos;\n"
    "            float d = length(toLight);\n"
    "            L = toLight / max(d, 0.0001);\n"
    "            if (uLights[i].range > 0.0) { float r = d / uLights[i].range; atten = max(1.0 - r * r, 0.0); atten *= "
    "atten; }\n"
    "            else atten = 1.0 / (d * d + 0.0001);\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                atten *= (abs(eps) < 0.0001) ? float(cosA >= uLights[i].outerCutoff)\n"
    "                                             : clamp((cosA - uLights[i].outerCutoff) / eps, 0.0, 1.0);\n"
    "            } }\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        lit += uLights[i].color * uLights[i].intensity * NdotL * atten;\n"
    "    }\n"
    "    vColor = vec4(min(lit, 1.0) * aColor.rgb, aColor.a);\n"
    "    float dist = length(uCameraPos - worldPos);\n"
    "    vFogFactor = 0.0;\n"
    "    if (uFogMode == 1) vFogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "    else if (uFogMode == 2) vFogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "    else if (uFogMode == 3) { float d = uFogDensity * dist; vFogFactor = 1.0 - exp(-d * d); }\n"
    "}\n";

static const char *sdl3d_shader_dos_frag =
    "noperspective in vec2 vTexCoord;\n"
    "flat in vec4 vColor;\n"
    "in float vFogFactor;\n"
    "uniform sampler2D uTexture;\n"
    "uniform int uHasTexture;\n"
    "uniform vec4 uTint;\n"
    "uniform vec3 uFogColor;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
    "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
    "    vec3 color = texel.rgb * vColor.rgb * uTint.rgb;\n"
    "    float alpha = texel.a * vColor.a * uTint.a;\n"
    "    if (alpha <= 0.0) discard;\n"
    "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
    "    color = mix(color, uFogColor, vFogFactor);\n"
    "    /* DOS VGA: 6-level per channel (216 colors) + heavy Bayer dither. */\n"
    "    float bayer[16] = float[16](0.0/16.0, 8.0/16.0, 2.0/16.0, 10.0/16.0,\n"
    "                                12.0/16.0, 4.0/16.0, 14.0/16.0, 6.0/16.0,\n"
    "                                3.0/16.0, 11.0/16.0, 1.0/16.0, 9.0/16.0,\n"
    "                                15.0/16.0, 7.0/16.0, 13.0/16.0, 5.0/16.0);\n"
    "    ivec2 px = ivec2(gl_FragCoord.xy);\n"
    "    float dither = (bayer[(px.y % 4) * 4 + (px.x % 4)] - 0.5) / 5.0;\n"
    "    color = floor((color + dither) * 6.0 + 0.5) / 6.0;\n"
    "    /* Desaturate toward VGA palette feel. */\n"
    "    float lum = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "    color = mix(vec3(lum), color, 0.7);\n"
    "    /* Slight warm CRT tint. */\n"
    "    color *= vec3(1.05, 0.98, 0.9);\n"
    "    fragColor = vec4(max(color, 0.0), alpha);\n"
    "}\n";

/* ================================================================== */
/* SNES shader: flat shading + affine + vertex fog + 5-bit color      */
/* ================================================================== */

static const char *sdl3d_shader_snes_vert =
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aTexCoord;\n"
    "layout(location = 3) in vec4 aColor;\n"
    "uniform mat4 uMVP;\n"
    "uniform mat4 uModel;\n"
    "uniform mat3 uNormalMatrix;\n"
    "uniform vec3 uCameraPos;\n"
    "uniform vec3 uAmbient;\n"
    "uniform int uLightCount;\n"
    "struct Light { int type; vec3 position; vec3 direction; vec3 color;\n"
    "    float intensity; float range; float innerCutoff; float outerCutoff; };\n"
    "uniform Light uLights[8];\n"
    "uniform int uFogMode;\n"
    "uniform float uFogStart;\n"
    "uniform float uFogEnd;\n"
    "uniform float uFogDensity;\n"
    "noperspective out vec2 vTexCoord;\n"
    "flat out vec4 vColor;\n"
    "out float vFogFactor;\n"
    "void main() {\n"
    "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
    "    vTexCoord = aTexCoord;\n"
    "    vec3 worldPos = (uModel * vec4(aPosition, 1.0)).xyz;\n"
    "    vec3 N = normalize(uNormalMatrix * aNormal);\n"
    "    vec3 lit = uAmbient;\n"
    "    for (int i = 0; i < uLightCount && i < 8; ++i) {\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (uLights[i].type == 0) { L = -normalize(uLights[i].direction); }\n"
    "        else { vec3 toLight = uLights[i].position - worldPos;\n"
    "            float d = length(toLight);\n"
    "            L = toLight / max(d, 0.0001);\n"
    "            if (uLights[i].range > 0.0) { float r = d / uLights[i].range; atten = max(1.0 - r * r, 0.0); atten *= "
    "atten; }\n"
    "            else atten = 1.0 / (d * d + 0.0001);\n"
    "            if (uLights[i].type == 2) {\n"
    "                float cosA = dot(-L, normalize(uLights[i].direction));\n"
    "                float eps = uLights[i].innerCutoff - uLights[i].outerCutoff;\n"
    "                atten *= (abs(eps) < 0.0001) ? float(cosA >= uLights[i].outerCutoff)\n"
    "                                             : clamp((cosA - uLights[i].outerCutoff) / eps, 0.0, 1.0);\n"
    "            } }\n"
    "        float NdotL = max(dot(N, L), 0.0);\n"
    "        lit += uLights[i].color * uLights[i].intensity * NdotL * atten;\n"
    "    }\n"
    "    vColor = vec4(min(lit, 1.0) * aColor.rgb, aColor.a);\n"
    "    float dist = length(uCameraPos - worldPos);\n"
    "    vFogFactor = 0.0;\n"
    "    if (uFogMode == 1) vFogFactor = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);\n"
    "    else if (uFogMode == 2) vFogFactor = 1.0 - exp(-uFogDensity * dist);\n"
    "    else if (uFogMode == 3) { float d = uFogDensity * dist; vFogFactor = 1.0 - exp(-d * d); }\n"
    "}\n";

static const char *sdl3d_shader_snes_frag = "noperspective in vec2 vTexCoord;\n"
                                            "flat in vec4 vColor;\n"
                                            "in float vFogFactor;\n"
                                            "uniform sampler2D uTexture;\n"
                                            "uniform int uHasTexture;\n"
                                            "uniform vec4 uTint;\n"
                                            "uniform vec3 uFogColor;\n"
                                            "out vec4 fragColor;\n"
                                            "void main() {\n"
                                            "    vec2 uv = vec2(vTexCoord.x, 1.0 - vTexCoord.y);\n"
                                            "    vec4 texel = (uHasTexture != 0) ? texture(uTexture, uv) : vec4(1.0);\n"
                                            "    vec3 color = texel.rgb * vColor.rgb * uTint.rgb;\n"
                                            "    float alpha = texel.a * vColor.a * uTint.a;\n"
                                            "    if (alpha <= 0.0) discard;\n"
                                            "    color = pow(clamp(color, 0.0, 1.0), vec3(1.0/2.2));\n"
                                            "    color = mix(color, uFogColor, vFogFactor);\n"
                                            "    /* SNES: 5-bit per channel (15-bit color). */\n"
                                            "    color = floor(color * 32.0 + 0.5) / 32.0;\n"
                                            "    /* Scanline darkening — every other row. */\n"
                                            "    int row = int(gl_FragCoord.y);\n"
                                            "    if ((row & 1) == 0) color *= 0.82;\n"
                                            "    /* Slight cool tint — SNES had a blue-ish palette bias. */\n"
                                            "    color *= vec3(0.95, 0.97, 1.05);\n"
                                            "    fragColor = vec4(color, alpha);\n"
                                            "}\n";

/* ================================================================== */
/* Shadow depth pass: position-only, writes depth to FBO              */
/* ================================================================== */

static const char *sdl3d_shader_shadow_vert = "layout(location = 0) in vec3 aPosition;\n"
                                              "uniform mat4 uMVP;\n"
                                              "void main() {\n"
                                              "    gl_Position = uMVP * vec4(aPosition, 1.0);\n"
                                              "}\n";

static const char *sdl3d_shader_shadow_frag = "out vec4 fragColor;\n"
                                              "void main() {\n"
                                              "    fragColor = vec4(1.0);\n"
                                              "}\n";

/* ================================================================== */
/* Fullscreen shaders for present and post-processing                  */
/* ================================================================== */

static const char *sdl3d_shader_fullscreen_vert = "out vec2 vTexCoord;\n"
                                                  "void main() {\n"
                                                  "    /* Fullscreen triangle covering the viewport. */\n"
                                                  "    float x = float((gl_VertexID & 1) << 2) - 1.0;\n"
                                                  "    float y = float((gl_VertexID & 2) << 1) - 1.0;\n"
                                                  "    vTexCoord = vec2(x * 0.5 + 0.5, y * 0.5 + 0.5);\n"
                                                  "    gl_Position = vec4(x, y, 0.0, 1.0);\n"
                                                  "}\n";

static const char *sdl3d_shader_copy_frag = "in vec2 vTexCoord;\n"
                                            "uniform sampler2D uScene;\n"
                                            "out vec4 fragColor;\n"
                                            "void main() {\n"
                                            "    fragColor = texture(uScene, vTexCoord);\n"
                                            "}\n";

static const char *sdl3d_shader_postprocess_frag =
    "in vec2 vTexCoord;\n"
    "uniform sampler2D uScene;\n"
    "uniform vec2 uTexelSize;\n"
    "uniform int uEffects;\n"
    "uniform float uBloomThreshold;\n"
    "uniform float uBloomIntensity;\n"
    "uniform float uVignetteIntensity;\n"
    "uniform float uContrast;\n"
    "uniform float uBrightness;\n"
    "uniform float uSaturation;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec4 scene = texture(uScene, vTexCoord);\n"
    "    vec3 color = scene.rgb;\n"
    "    float alpha = scene.a;\n"
    "    /* Bloom: simple 5-tap cross blur of bright pixels. */\n"
    "    if ((uEffects & 1) != 0) {\n"
    "        vec3 bloom = vec3(0.0);\n"
    "        for (int i = -2; i <= 2; ++i) {\n"
    "            for (int j = -2; j <= 2; ++j) {\n"
    "                vec3 s = texture(uScene, vTexCoord + vec2(float(i), float(j)) * uTexelSize).rgb;\n"
    "                float lum = dot(s, vec3(0.2126, 0.7152, 0.0722));\n"
    "                if (lum > uBloomThreshold) bloom += s;\n"
    "            }\n"
    "        }\n"
    "        color += bloom * uBloomIntensity / 25.0;\n"
    "    }\n"
    "    /* Vignette. */\n"
    "    if ((uEffects & 2) != 0) {\n"
    "        vec2 uv = vTexCoord * 2.0 - 1.0;\n"
    "        float d = dot(uv, uv) * 0.5;\n"
    "        color *= max(1.0 - d * uVignetteIntensity, 0.0);\n"
    "    }\n"
    "    /* Color grading. */\n"
    "    if ((uEffects & 4) != 0) {\n"
    "        color = (color - 0.5) * uContrast + 0.5 + uBrightness;\n"
    "        float gray = dot(color, vec3(0.2126, 0.7152, 0.0722));\n"
    "        color = mix(vec3(gray), color, uSaturation);\n"
    "    }\n"
    "    fragColor = vec4(max(color, 0.0), alpha);\n"
    "}\n";
