name: CI

on:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup SDL
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-latest
          install-linux-dependencies: true

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Test
        if: runner.os != 'Linux'
        run: ctest --preset release

      - name: Test
        if: runner.os == 'Linux'
        run: xvfb-run -a ctest --preset release

  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure
        run: >
          emcmake cmake -S . -B build/emscripten
          -DCMAKE_BUILD_TYPE=Release
          -DSDL3D_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build/emscripten

      - name: Test
        run: |
          set -e
          for t in build/emscripten/tests/*.js; do
            echo "::group::$t"
            node "$t"
            echo "::endgroup::"
          done

  sanitizers:
    name: Sanitizers
    runs-on: ubuntu-latest

    env:
      CC: clang
      ASAN_OPTIONS: detect_leaks=1
      UBSAN_OPTIONS: print_stacktrace=1

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install --yes clang ninja-build xvfb

      - name: Setup SDL
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-latest
          install-linux-dependencies: true

      - name: Configure
        run: cmake --preset sanitizers

      - name: Build
        run: cmake --build --preset sanitizers

      - name: Test
        run: xvfb-run -a ctest --preset sanitizers
